### ISSUE TITLE
쿠키 expire 시간 조정해야 할걸요

### ISSUE THREAD

**Issue by 2woongjae** [surfesta/surfesta#121]

**Comment by domuk-k** [comment]
익스프레스 / 익스프레스에서의 쿠키 처리를 위한 cookie-parser와 관련한 내용을 읽고 해결했습니다.
- https://expressjs.com/en/api.html#res.cookie
- https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-4.1.1
`4.1.1.  "Strict" and "Lax" enforcement
   By default, same-site cookies will not be sent along with top-level
   navigations.  As discussed in Section 5.2, this might or might not be
   compatible with existing session management systems.  In the
   interests of providing a drop-in mechanism that mitigates the risk of
   CSRF attacks, developers may set the "SameSite" attribute in a "Lax"
   enforcement mode that carves out an exception which sends same-site
   cookies along with cross-site requests if and only if they are top-
   level navigations which use a "safe" (in the [RFC7231] sense) HTTP
   method.
   Lax enforcement provides reasonable defense in depth against CSRF
   attacks that rely on unsafe HTTP methods (like "POST"), but do not
   offer a robust defense against CSRF as a general category of attack:`
