### ISSUE TITLE
feat: img 폴더 경로 수정

### ISSUE THREAD

**Issue by tinkerbell93** [surfesta/surfesta#146]
기존 img 폴더를 src img폴더에서 public img폴더로 이동하려고 합니다. 
src img에서 이미지를 넣고 사용하셨다면 public img로 옮기고 사용해주세요.
현재 public img폴더 생성해 놓았습니다.

완료가 되었다면 댓글 남겨주세요. 
모두 확인이 되면 src img 폴더 삭제하겠습니다.

**Comment by domuk-k** [comment]
네 전 img폴더 안씁니다

**Comment by domuk-k** [comment]
svg이미지는 가능하면 SVGR - SVG to React 이 vscode extension으로 **컴포넌트**로 만들어서 쓰시면 좋을거같아요
