### ISSUE TITLE
index.html, server.js, package.json, client/component 수정

### ISSUE THREAD

**Issue by Dev-UB** [surfesta/surfesta#26]
index파일에서 CDN으로 구글맵 api 가져오고있는데 다른 방법을 찾아봐야할까요? 현재 이슈는 토스트 에디터 컨텐츠랑 구글맵 정보를 어떤식으로 저장해야하나 고민이네여

**Comment by domuk-k** [comment]
네 CDN없이 API_KEY는 환경변수에 숨겨두고 [구글api를](https://www.npmjs.com/package/googleapis) 사용해야겠습니다.

문자열로 저장하면, 안되는 이유가 있어서 그러시는 건가요?
에디터 컨텐츠는 h1등 포맷이 저장이 안되는 문제가 있을 수 있을거 같고, 위치정보는 문제없을 거 같은데,
명확하게 문제제기 해주시기바랍니다.

이슈 제목은 파일명보다는 구현한 기능 또는 버그이슈에 대해 작성해주셔야 이해가 쉽습니다. 어떤 파일이 변경되었는지는 풀리퀘스트 기록에서 더 쉽게 볼 수 있습니다.
