### ISSUE TITLE
패키치 따로 제가 설치한 내용입니다.

### ISSUE THREAD

**Issue by Dev-UB** [surfesta/surfesta#4]
- server
    "express-fileupload": "^1.2.0",

- client
    "@toast-ui/react-editor": "^2.3.1",
    "axios": "^0.20.0",
    "node-sass": "^4.14.1",
    "tui-editor": "^1.4.10",
    "use-places-autocomplete": "^1.3.10"

nodemon은 따로 안깔고 실행할때 npx로 돌려도 상관 없나요? 그렇게 되어있더라구욥

**Comment by domuk-k** [comment]
네 그게 바로 npx의 역할입니다. 워낙 가벼운 모듈이라 굳이 다운받지않고 필요할때 npx로 임시로 다운받아서 실행시킵니다.
npx create-react-app 도 마찬가지로, 설치용파일 자체는 가볍기때문에 굳이 받지않습니다
