### ISSUE TITLE
client-styling 텍스트로고 폰트제안

### ISSUE THREAD

**Issue by domuk-k** [surfesta/surfesta#40]
[YellowFont](https://fonts.google.com/specimen/Yellowtail?preview.text=Surfesta&preview.text_type=custom#standard-styles)

**Comment by tinkerbell93** [comment]
[Damion](https://fonts.google.com/specimen/Damion?preview.text=Surfesta&preview.text_type=custom&category=Handwriting)

**Comment by domuk-k** [comment]
Resolved #40
